### ISSUE TITLE
`subject()` removed from 5.x

### ISSUE THREAD

**Issue by jonny-improbable** [mostjs-community/subject#33]
In `most-subject` 4.1.3 our codebase was making use of the following pattern to create an imperative stream which we could push new events to:

```js
import { subject } from 'most-subject';
const $authToken = subject();
$authToken.next("hello!");
```

This factory function has been removed from the 5.x API with no mention made to it in the CHANGELOG; looking at the code in the [4.1.1 tag](https://github.com/mostjs-community/subject/tree/v4.1.1) it would appear that the migration should be:

```js
import { asAsync, BasicSubjectSource } from 'most-subject';
const $authToken = asAsync(new BasicSubjectSource())
```

However as of 5.2 `BasicSubjectSource` appears to have been removed from the exported API - was this intentional?  If so is there a migration path for the above code?

Thanks!

**Comment by TylorS** [comment]
The breaking change was intentional to add support for async emitting subjects, greatly simplify internal implementation, and improve the TypeScript definitions. 

The exact equivalent to `subject` is `sync`. 

```typescript
import { sync } from 'subject'

const authToken$ = sync()

authToken$.next('hello!')
```

Hope this helps!

**Comment by TylorS** [comment]
Closing this as its stale...

Feel free to reopen if you're having any further issues.
