### ISSUE TITLE
Please could we add a umd build?

### ISSUE THREAD

**Issue by ctrlplusb** [mostjs-community/subject#34]
😇

I would have done so myself, but TS is unfamiliar to me.

**Comment by wishfoundry** [comment]
@ctrlplusb not that hard, just need to set 
` {"module": "umd" }` 
in a new tsconfig.json, and add a link the in the scripts of the package.json

**Comment by ctrlplusb** [comment]
Unfortunately it seems more fiddly than an output target change.  I've been doing tons of trial and error on this but can't get things quite right.

Ideally I would like us to create two single file outputs:

```
lib
 |- umd
     |- most-subject.js
     |- most-subject.min.js
```

So we may need to run a Typescript compile and then uglify the result to get the "min" version.

I am giving up on this again for now.  If anyone experienced with Typescript sees this I would appreciate it if they gave it a look.  I'll try again at some point, however, I have other things calling my name right now, i.e. the kids. :D

**Comment by ctrlplusb** [comment]
Another option could be to use `rollup` and `uglifyjs` on the commonjs output.  Would this be opposed? If not I could do that.

**Comment by TylorS** [comment]
Yeah, I'm cool with creating a rollup build, that's inline with what the rest of most.js is doing :+1: 

> Another option could be to use rollup and uglifyjs on the commonjs output

I would actually use `rollup-plugin-typescript` and rollup directly from the source code and would build it into a `dist` folder to allow it to be uploaded here on github with the other files. 

If you're up for the challenge, I'd definitely be interested in getting it merged. Thanks!

**Comment by TylorS** [comment]
I actually tackled this :)
There is now a UMD build in the `dist/` folder.
