### ISSUE TITLE
Cyclic stream never finishes

### ISSUE THREAD

**Issue by ludekstepan** [mostjs-community/subject#37]
Hello,

I'm trying to use the `@most/core` together with the `most-subject` to implement a state reducer loop and epic similar to the `redux-most`.

I've got the basic concept working, but the stream never ends when there is a cyclic dependency even when the initial stream closes.

```typescript
import { attach, create } from 'most-subject'
import { filter, map, merge, now } from '@most/core'
import { Time } from '@most/types'
import { newDefaultScheduler } from '@most/scheduler'

const input = now(5)

const [ sink, stream ] = create<number>()
const combined = merge(input, stream)
const feedback = map(a => a * 2, filter(a => a % 2 === 1, combined))

attach(sink, feedback)

combined.run({
    end(): void {
        console.log('loop ended')
    },
    error(time, err: Error): void {
        console.log('error', err)
    },
    event(time, value): void {
        console.log('event', value)
    }
}, newDefaultScheduler())

```

The output is:
```
event 5
event 10
```

The expected output:
```
event 5
event 10
loop ended
```

Do you have any idea what is wrong? I'm not sure if this is even possible, but it would be great!

**Comment by ludekstepan** [comment]
I found that the problem is caused by the `merge` operator not passing through the end signal since only one if its streams has ended and it has no knowledge that the other argument is circular dependency of the first.

I was able to overcome this issue by extracting the end signal from the input stream and combining it with the feedback signal.

```typescript
// ...
const end = continueWith(() => now(null), filter(() => false, input))
const combined = merge(input, until(end, stream))
// ...
```

**Comment by TylorS** [comment]
Hey @ludekstepan, thanks for posting your findings here, which are 100% on point 👍 
Most doesn't currently have any simple mechanisms for tracing a stream-graph, though it might in the future https://github.com/mostjs/core/pull/211, so ensuring circular dependencies were the `stream` itself is a dependency used to `attach` does need some manual cleaning up at times. We should absolutely document this behavior.
